// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopLevelData.proto

public final class TopLevelDataOuterClass {
  private TopLevelDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TopLevelDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TopLevelData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.WordMessage wordMessage = 4;</code>
     * @return Whether the wordMessage field is set.
     */
    boolean hasWordMessage();
    /**
     * <code>.WordMessage wordMessage = 4;</code>
     * @return The wordMessage.
     */
    WordMessageOuterClass.WordMessage getWordMessage();
    /**
     * <code>.WordMessage wordMessage = 4;</code>
     */
    WordMessageOuterClass.WordMessageOrBuilder getWordMessageOrBuilder();

    /**
     * <code>.VideoMessage videoMessage = 5;</code>
     * @return Whether the videoMessage field is set.
     */
    boolean hasVideoMessage();
    /**
     * <code>.VideoMessage videoMessage = 5;</code>
     * @return The videoMessage.
     */
    VideoMessageOuterClass.VideoMessage getVideoMessage();
    /**
     * <code>.VideoMessage videoMessage = 5;</code>
     */
    VideoMessageOuterClass.VideoMessageOrBuilder getVideoMessageOrBuilder();

    /**
     * <code>.AudioMessage audioMessage = 6;</code>
     * @return Whether the audioMessage field is set.
     */
    boolean hasAudioMessage();
    /**
     * <code>.AudioMessage audioMessage = 6;</code>
     * @return The audioMessage.
     */
    AudioMessageOuterClass.AudioMessage getAudioMessage();
    /**
     * <code>.AudioMessage audioMessage = 6;</code>
     */
    AudioMessageOuterClass.AudioMessageOrBuilder getAudioMessageOrBuilder();

    /**
     * <code>.FileMessage fileMessage = 7;</code>
     * @return Whether the fileMessage field is set.
     */
    boolean hasFileMessage();
    /**
     * <code>.FileMessage fileMessage = 7;</code>
     * @return The fileMessage.
     */
    FileMessageOuterClass.FileMessage getFileMessage();
    /**
     * <code>.FileMessage fileMessage = 7;</code>
     */
    FileMessageOuterClass.FileMessageOrBuilder getFileMessageOrBuilder();

    /**
     * <code>.TopLevelData.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.TopLevelData.Type type = 1;</code>
     * @return The type.
     */
    TopLevelDataOuterClass.TopLevelData.Type getType();

    /**
     * <code>fixed64 sendTime = 2;</code>
     * @return The sendTime.
     */
    long getSendTime();

    public TopLevelDataOuterClass.TopLevelData.MessageCase getMessageCase();
  }
  /**
   * Protobuf type {@code TopLevelData}
   */
  public  static final class TopLevelData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TopLevelData)
      TopLevelDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopLevelData.newBuilder() to construct.
    private TopLevelData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopLevelData() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TopLevelData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TopLevelData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 17: {

              sendTime_ = input.readFixed64();
              break;
            }
            case 34: {
              WordMessageOuterClass.WordMessage.Builder subBuilder = null;
              if (messageCase_ == 4) {
                subBuilder = ((WordMessageOuterClass.WordMessage) message_).toBuilder();
              }
              message_ =
                  input.readMessage(WordMessageOuterClass.WordMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((WordMessageOuterClass.WordMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 4;
              break;
            }
            case 42: {
              VideoMessageOuterClass.VideoMessage.Builder subBuilder = null;
              if (messageCase_ == 5) {
                subBuilder = ((VideoMessageOuterClass.VideoMessage) message_).toBuilder();
              }
              message_ =
                  input.readMessage(VideoMessageOuterClass.VideoMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((VideoMessageOuterClass.VideoMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 5;
              break;
            }
            case 50: {
              AudioMessageOuterClass.AudioMessage.Builder subBuilder = null;
              if (messageCase_ == 6) {
                subBuilder = ((AudioMessageOuterClass.AudioMessage) message_).toBuilder();
              }
              message_ =
                  input.readMessage(AudioMessageOuterClass.AudioMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((AudioMessageOuterClass.AudioMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 6;
              break;
            }
            case 58: {
              FileMessageOuterClass.FileMessage.Builder subBuilder = null;
              if (messageCase_ == 7) {
                subBuilder = ((FileMessageOuterClass.FileMessage) message_).toBuilder();
              }
              message_ =
                  input.readMessage(FileMessageOuterClass.FileMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((FileMessageOuterClass.FileMessage) message_);
                message_ = subBuilder.buildPartial();
              }
              messageCase_ = 7;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TopLevelDataOuterClass.internal_static_TopLevelData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TopLevelDataOuterClass.internal_static_TopLevelData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TopLevelDataOuterClass.TopLevelData.class, TopLevelDataOuterClass.TopLevelData.Builder.class);
    }

    /**
     * Protobuf enum {@code TopLevelData.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>WORD = 0;</code>
       */
      WORD(0),
      /**
       * <code>AUDIO = 1;</code>
       */
      AUDIO(1),
      /**
       * <code>VIDEO = 2;</code>
       */
      VIDEO(2),
      /**
       * <code>FILE = 3;</code>
       */
      FILE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>WORD = 0;</code>
       */
      public static final int WORD_VALUE = 0;
      /**
       * <code>AUDIO = 1;</code>
       */
      public static final int AUDIO_VALUE = 1;
      /**
       * <code>VIDEO = 2;</code>
       */
      public static final int VIDEO_VALUE = 2;
      /**
       * <code>FILE = 3;</code>
       */
      public static final int FILE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Type forNumber(int value) {
        switch (value) {
          case 0: return WORD;
          case 1: return AUDIO;
          case 2: return VIDEO;
          case 3: return FILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return TopLevelDataOuterClass.TopLevelData.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:TopLevelData.Type)
    }

    private int messageCase_ = 0;
    private java.lang.Object message_;
    public enum MessageCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      WORDMESSAGE(4),
      VIDEOMESSAGE(5),
      AUDIOMESSAGE(6),
      FILEMESSAGE(7),
      MESSAGE_NOT_SET(0);
      private final int value;
      private MessageCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageCase forNumber(int value) {
        switch (value) {
          case 4: return WORDMESSAGE;
          case 5: return VIDEOMESSAGE;
          case 6: return AUDIOMESSAGE;
          case 7: return FILEMESSAGE;
          case 0: return MESSAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MessageCase
    getMessageCase() {
      return MessageCase.forNumber(
          messageCase_);
    }

    public static final int WORDMESSAGE_FIELD_NUMBER = 4;
    /**
     * <code>.WordMessage wordMessage = 4;</code>
     * @return Whether the wordMessage field is set.
     */
    public boolean hasWordMessage() {
      return messageCase_ == 4;
    }
    /**
     * <code>.WordMessage wordMessage = 4;</code>
     * @return The wordMessage.
     */
    public WordMessageOuterClass.WordMessage getWordMessage() {
      if (messageCase_ == 4) {
         return (WordMessageOuterClass.WordMessage) message_;
      }
      return WordMessageOuterClass.WordMessage.getDefaultInstance();
    }
    /**
     * <code>.WordMessage wordMessage = 4;</code>
     */
    public WordMessageOuterClass.WordMessageOrBuilder getWordMessageOrBuilder() {
      if (messageCase_ == 4) {
         return (WordMessageOuterClass.WordMessage) message_;
      }
      return WordMessageOuterClass.WordMessage.getDefaultInstance();
    }

    public static final int VIDEOMESSAGE_FIELD_NUMBER = 5;
    /**
     * <code>.VideoMessage videoMessage = 5;</code>
     * @return Whether the videoMessage field is set.
     */
    public boolean hasVideoMessage() {
      return messageCase_ == 5;
    }
    /**
     * <code>.VideoMessage videoMessage = 5;</code>
     * @return The videoMessage.
     */
    public VideoMessageOuterClass.VideoMessage getVideoMessage() {
      if (messageCase_ == 5) {
         return (VideoMessageOuterClass.VideoMessage) message_;
      }
      return VideoMessageOuterClass.VideoMessage.getDefaultInstance();
    }
    /**
     * <code>.VideoMessage videoMessage = 5;</code>
     */
    public VideoMessageOuterClass.VideoMessageOrBuilder getVideoMessageOrBuilder() {
      if (messageCase_ == 5) {
         return (VideoMessageOuterClass.VideoMessage) message_;
      }
      return VideoMessageOuterClass.VideoMessage.getDefaultInstance();
    }

    public static final int AUDIOMESSAGE_FIELD_NUMBER = 6;
    /**
     * <code>.AudioMessage audioMessage = 6;</code>
     * @return Whether the audioMessage field is set.
     */
    public boolean hasAudioMessage() {
      return messageCase_ == 6;
    }
    /**
     * <code>.AudioMessage audioMessage = 6;</code>
     * @return The audioMessage.
     */
    public AudioMessageOuterClass.AudioMessage getAudioMessage() {
      if (messageCase_ == 6) {
         return (AudioMessageOuterClass.AudioMessage) message_;
      }
      return AudioMessageOuterClass.AudioMessage.getDefaultInstance();
    }
    /**
     * <code>.AudioMessage audioMessage = 6;</code>
     */
    public AudioMessageOuterClass.AudioMessageOrBuilder getAudioMessageOrBuilder() {
      if (messageCase_ == 6) {
         return (AudioMessageOuterClass.AudioMessage) message_;
      }
      return AudioMessageOuterClass.AudioMessage.getDefaultInstance();
    }

    public static final int FILEMESSAGE_FIELD_NUMBER = 7;
    /**
     * <code>.FileMessage fileMessage = 7;</code>
     * @return Whether the fileMessage field is set.
     */
    public boolean hasFileMessage() {
      return messageCase_ == 7;
    }
    /**
     * <code>.FileMessage fileMessage = 7;</code>
     * @return The fileMessage.
     */
    public FileMessageOuterClass.FileMessage getFileMessage() {
      if (messageCase_ == 7) {
         return (FileMessageOuterClass.FileMessage) message_;
      }
      return FileMessageOuterClass.FileMessage.getDefaultInstance();
    }
    /**
     * <code>.FileMessage fileMessage = 7;</code>
     */
    public FileMessageOuterClass.FileMessageOrBuilder getFileMessageOrBuilder() {
      if (messageCase_ == 7) {
         return (FileMessageOuterClass.FileMessage) message_;
      }
      return FileMessageOuterClass.FileMessage.getDefaultInstance();
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.TopLevelData.Type type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.TopLevelData.Type type = 1;</code>
     * @return The type.
     */
    public TopLevelDataOuterClass.TopLevelData.Type getType() {
      @SuppressWarnings("deprecation")
      TopLevelDataOuterClass.TopLevelData.Type result = TopLevelDataOuterClass.TopLevelData.Type.valueOf(type_);
      return result == null ? TopLevelDataOuterClass.TopLevelData.Type.UNRECOGNIZED : result;
    }

    public static final int SENDTIME_FIELD_NUMBER = 2;
    private long sendTime_;
    /**
     * <code>fixed64 sendTime = 2;</code>
     * @return The sendTime.
     */
    public long getSendTime() {
      return sendTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != TopLevelDataOuterClass.TopLevelData.Type.WORD.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (sendTime_ != 0L) {
        output.writeFixed64(2, sendTime_);
      }
      if (messageCase_ == 4) {
        output.writeMessage(4, (WordMessageOuterClass.WordMessage) message_);
      }
      if (messageCase_ == 5) {
        output.writeMessage(5, (VideoMessageOuterClass.VideoMessage) message_);
      }
      if (messageCase_ == 6) {
        output.writeMessage(6, (AudioMessageOuterClass.AudioMessage) message_);
      }
      if (messageCase_ == 7) {
        output.writeMessage(7, (FileMessageOuterClass.FileMessage) message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != TopLevelDataOuterClass.TopLevelData.Type.WORD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(2, sendTime_);
      }
      if (messageCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (WordMessageOuterClass.WordMessage) message_);
      }
      if (messageCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (VideoMessageOuterClass.VideoMessage) message_);
      }
      if (messageCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (AudioMessageOuterClass.AudioMessage) message_);
      }
      if (messageCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, (FileMessageOuterClass.FileMessage) message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TopLevelDataOuterClass.TopLevelData)) {
        return super.equals(obj);
      }
      TopLevelDataOuterClass.TopLevelData other = (TopLevelDataOuterClass.TopLevelData) obj;

      if (type_ != other.type_) return false;
      if (getSendTime()
          != other.getSendTime()) return false;
      if (!getMessageCase().equals(other.getMessageCase())) return false;
      switch (messageCase_) {
        case 4:
          if (!getWordMessage()
              .equals(other.getWordMessage())) return false;
          break;
        case 5:
          if (!getVideoMessage()
              .equals(other.getVideoMessage())) return false;
          break;
        case 6:
          if (!getAudioMessage()
              .equals(other.getAudioMessage())) return false;
          break;
        case 7:
          if (!getFileMessage()
              .equals(other.getFileMessage())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      switch (messageCase_) {
        case 4:
          hash = (37 * hash) + WORDMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getWordMessage().hashCode();
          break;
        case 5:
          hash = (37 * hash) + VIDEOMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getVideoMessage().hashCode();
          break;
        case 6:
          hash = (37 * hash) + AUDIOMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getAudioMessage().hashCode();
          break;
        case 7:
          hash = (37 * hash) + FILEMESSAGE_FIELD_NUMBER;
          hash = (53 * hash) + getFileMessage().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TopLevelDataOuterClass.TopLevelData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopLevelDataOuterClass.TopLevelData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopLevelDataOuterClass.TopLevelData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopLevelDataOuterClass.TopLevelData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopLevelDataOuterClass.TopLevelData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TopLevelDataOuterClass.TopLevelData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TopLevelDataOuterClass.TopLevelData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TopLevelDataOuterClass.TopLevelData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TopLevelDataOuterClass.TopLevelData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TopLevelDataOuterClass.TopLevelData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TopLevelDataOuterClass.TopLevelData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TopLevelDataOuterClass.TopLevelData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TopLevelDataOuterClass.TopLevelData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TopLevelData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TopLevelData)
        TopLevelDataOuterClass.TopLevelDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TopLevelDataOuterClass.internal_static_TopLevelData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TopLevelDataOuterClass.internal_static_TopLevelData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TopLevelDataOuterClass.TopLevelData.class, TopLevelDataOuterClass.TopLevelData.Builder.class);
      }

      // Construct using TopLevelDataOuterClass.TopLevelData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        sendTime_ = 0L;

        messageCase_ = 0;
        message_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TopLevelDataOuterClass.internal_static_TopLevelData_descriptor;
      }

      @java.lang.Override
      public TopLevelDataOuterClass.TopLevelData getDefaultInstanceForType() {
        return TopLevelDataOuterClass.TopLevelData.getDefaultInstance();
      }

      @java.lang.Override
      public TopLevelDataOuterClass.TopLevelData build() {
        TopLevelDataOuterClass.TopLevelData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public TopLevelDataOuterClass.TopLevelData buildPartial() {
        TopLevelDataOuterClass.TopLevelData result = new TopLevelDataOuterClass.TopLevelData(this);
        if (messageCase_ == 4) {
          if (wordMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = wordMessageBuilder_.build();
          }
        }
        if (messageCase_ == 5) {
          if (videoMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = videoMessageBuilder_.build();
          }
        }
        if (messageCase_ == 6) {
          if (audioMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = audioMessageBuilder_.build();
          }
        }
        if (messageCase_ == 7) {
          if (fileMessageBuilder_ == null) {
            result.message_ = message_;
          } else {
            result.message_ = fileMessageBuilder_.build();
          }
        }
        result.type_ = type_;
        result.sendTime_ = sendTime_;
        result.messageCase_ = messageCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TopLevelDataOuterClass.TopLevelData) {
          return mergeFrom((TopLevelDataOuterClass.TopLevelData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TopLevelDataOuterClass.TopLevelData other) {
        if (other == TopLevelDataOuterClass.TopLevelData.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        switch (other.getMessageCase()) {
          case WORDMESSAGE: {
            mergeWordMessage(other.getWordMessage());
            break;
          }
          case VIDEOMESSAGE: {
            mergeVideoMessage(other.getVideoMessage());
            break;
          }
          case AUDIOMESSAGE: {
            mergeAudioMessage(other.getAudioMessage());
            break;
          }
          case FILEMESSAGE: {
            mergeFileMessage(other.getFileMessage());
            break;
          }
          case MESSAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TopLevelDataOuterClass.TopLevelData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TopLevelDataOuterClass.TopLevelData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int messageCase_ = 0;
      private java.lang.Object message_;
      public MessageCase
          getMessageCase() {
        return MessageCase.forNumber(
            messageCase_);
      }

      public Builder clearMessage() {
        messageCase_ = 0;
        message_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          WordMessageOuterClass.WordMessage, WordMessageOuterClass.WordMessage.Builder, WordMessageOuterClass.WordMessageOrBuilder> wordMessageBuilder_;
      /**
       * <code>.WordMessage wordMessage = 4;</code>
       * @return Whether the wordMessage field is set.
       */
      public boolean hasWordMessage() {
        return messageCase_ == 4;
      }
      /**
       * <code>.WordMessage wordMessage = 4;</code>
       * @return The wordMessage.
       */
      public WordMessageOuterClass.WordMessage getWordMessage() {
        if (wordMessageBuilder_ == null) {
          if (messageCase_ == 4) {
            return (WordMessageOuterClass.WordMessage) message_;
          }
          return WordMessageOuterClass.WordMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 4) {
            return wordMessageBuilder_.getMessage();
          }
          return WordMessageOuterClass.WordMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.WordMessage wordMessage = 4;</code>
       */
      public Builder setWordMessage(WordMessageOuterClass.WordMessage value) {
        if (wordMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          wordMessageBuilder_.setMessage(value);
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>.WordMessage wordMessage = 4;</code>
       */
      public Builder setWordMessage(
          WordMessageOuterClass.WordMessage.Builder builderForValue) {
        if (wordMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          wordMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>.WordMessage wordMessage = 4;</code>
       */
      public Builder mergeWordMessage(WordMessageOuterClass.WordMessage value) {
        if (wordMessageBuilder_ == null) {
          if (messageCase_ == 4 &&
              message_ != WordMessageOuterClass.WordMessage.getDefaultInstance()) {
            message_ = WordMessageOuterClass.WordMessage.newBuilder((WordMessageOuterClass.WordMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 4) {
            wordMessageBuilder_.mergeFrom(value);
          }
          wordMessageBuilder_.setMessage(value);
        }
        messageCase_ = 4;
        return this;
      }
      /**
       * <code>.WordMessage wordMessage = 4;</code>
       */
      public Builder clearWordMessage() {
        if (wordMessageBuilder_ == null) {
          if (messageCase_ == 4) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 4) {
            messageCase_ = 0;
            message_ = null;
          }
          wordMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.WordMessage wordMessage = 4;</code>
       */
      public WordMessageOuterClass.WordMessage.Builder getWordMessageBuilder() {
        return getWordMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.WordMessage wordMessage = 4;</code>
       */
      public WordMessageOuterClass.WordMessageOrBuilder getWordMessageOrBuilder() {
        if ((messageCase_ == 4) && (wordMessageBuilder_ != null)) {
          return wordMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 4) {
            return (WordMessageOuterClass.WordMessage) message_;
          }
          return WordMessageOuterClass.WordMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.WordMessage wordMessage = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          WordMessageOuterClass.WordMessage, WordMessageOuterClass.WordMessage.Builder, WordMessageOuterClass.WordMessageOrBuilder> 
          getWordMessageFieldBuilder() {
        if (wordMessageBuilder_ == null) {
          if (!(messageCase_ == 4)) {
            message_ = WordMessageOuterClass.WordMessage.getDefaultInstance();
          }
          wordMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              WordMessageOuterClass.WordMessage, WordMessageOuterClass.WordMessage.Builder, WordMessageOuterClass.WordMessageOrBuilder>(
                  (WordMessageOuterClass.WordMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 4;
        onChanged();;
        return wordMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          VideoMessageOuterClass.VideoMessage, VideoMessageOuterClass.VideoMessage.Builder, VideoMessageOuterClass.VideoMessageOrBuilder> videoMessageBuilder_;
      /**
       * <code>.VideoMessage videoMessage = 5;</code>
       * @return Whether the videoMessage field is set.
       */
      public boolean hasVideoMessage() {
        return messageCase_ == 5;
      }
      /**
       * <code>.VideoMessage videoMessage = 5;</code>
       * @return The videoMessage.
       */
      public VideoMessageOuterClass.VideoMessage getVideoMessage() {
        if (videoMessageBuilder_ == null) {
          if (messageCase_ == 5) {
            return (VideoMessageOuterClass.VideoMessage) message_;
          }
          return VideoMessageOuterClass.VideoMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 5) {
            return videoMessageBuilder_.getMessage();
          }
          return VideoMessageOuterClass.VideoMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.VideoMessage videoMessage = 5;</code>
       */
      public Builder setVideoMessage(VideoMessageOuterClass.VideoMessage value) {
        if (videoMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          videoMessageBuilder_.setMessage(value);
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>.VideoMessage videoMessage = 5;</code>
       */
      public Builder setVideoMessage(
          VideoMessageOuterClass.VideoMessage.Builder builderForValue) {
        if (videoMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          videoMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>.VideoMessage videoMessage = 5;</code>
       */
      public Builder mergeVideoMessage(VideoMessageOuterClass.VideoMessage value) {
        if (videoMessageBuilder_ == null) {
          if (messageCase_ == 5 &&
              message_ != VideoMessageOuterClass.VideoMessage.getDefaultInstance()) {
            message_ = VideoMessageOuterClass.VideoMessage.newBuilder((VideoMessageOuterClass.VideoMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 5) {
            videoMessageBuilder_.mergeFrom(value);
          }
          videoMessageBuilder_.setMessage(value);
        }
        messageCase_ = 5;
        return this;
      }
      /**
       * <code>.VideoMessage videoMessage = 5;</code>
       */
      public Builder clearVideoMessage() {
        if (videoMessageBuilder_ == null) {
          if (messageCase_ == 5) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 5) {
            messageCase_ = 0;
            message_ = null;
          }
          videoMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.VideoMessage videoMessage = 5;</code>
       */
      public VideoMessageOuterClass.VideoMessage.Builder getVideoMessageBuilder() {
        return getVideoMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.VideoMessage videoMessage = 5;</code>
       */
      public VideoMessageOuterClass.VideoMessageOrBuilder getVideoMessageOrBuilder() {
        if ((messageCase_ == 5) && (videoMessageBuilder_ != null)) {
          return videoMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 5) {
            return (VideoMessageOuterClass.VideoMessage) message_;
          }
          return VideoMessageOuterClass.VideoMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.VideoMessage videoMessage = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          VideoMessageOuterClass.VideoMessage, VideoMessageOuterClass.VideoMessage.Builder, VideoMessageOuterClass.VideoMessageOrBuilder> 
          getVideoMessageFieldBuilder() {
        if (videoMessageBuilder_ == null) {
          if (!(messageCase_ == 5)) {
            message_ = VideoMessageOuterClass.VideoMessage.getDefaultInstance();
          }
          videoMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              VideoMessageOuterClass.VideoMessage, VideoMessageOuterClass.VideoMessage.Builder, VideoMessageOuterClass.VideoMessageOrBuilder>(
                  (VideoMessageOuterClass.VideoMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 5;
        onChanged();;
        return videoMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          AudioMessageOuterClass.AudioMessage, AudioMessageOuterClass.AudioMessage.Builder, AudioMessageOuterClass.AudioMessageOrBuilder> audioMessageBuilder_;
      /**
       * <code>.AudioMessage audioMessage = 6;</code>
       * @return Whether the audioMessage field is set.
       */
      public boolean hasAudioMessage() {
        return messageCase_ == 6;
      }
      /**
       * <code>.AudioMessage audioMessage = 6;</code>
       * @return The audioMessage.
       */
      public AudioMessageOuterClass.AudioMessage getAudioMessage() {
        if (audioMessageBuilder_ == null) {
          if (messageCase_ == 6) {
            return (AudioMessageOuterClass.AudioMessage) message_;
          }
          return AudioMessageOuterClass.AudioMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 6) {
            return audioMessageBuilder_.getMessage();
          }
          return AudioMessageOuterClass.AudioMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.AudioMessage audioMessage = 6;</code>
       */
      public Builder setAudioMessage(AudioMessageOuterClass.AudioMessage value) {
        if (audioMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          audioMessageBuilder_.setMessage(value);
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>.AudioMessage audioMessage = 6;</code>
       */
      public Builder setAudioMessage(
          AudioMessageOuterClass.AudioMessage.Builder builderForValue) {
        if (audioMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          audioMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>.AudioMessage audioMessage = 6;</code>
       */
      public Builder mergeAudioMessage(AudioMessageOuterClass.AudioMessage value) {
        if (audioMessageBuilder_ == null) {
          if (messageCase_ == 6 &&
              message_ != AudioMessageOuterClass.AudioMessage.getDefaultInstance()) {
            message_ = AudioMessageOuterClass.AudioMessage.newBuilder((AudioMessageOuterClass.AudioMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 6) {
            audioMessageBuilder_.mergeFrom(value);
          }
          audioMessageBuilder_.setMessage(value);
        }
        messageCase_ = 6;
        return this;
      }
      /**
       * <code>.AudioMessage audioMessage = 6;</code>
       */
      public Builder clearAudioMessage() {
        if (audioMessageBuilder_ == null) {
          if (messageCase_ == 6) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 6) {
            messageCase_ = 0;
            message_ = null;
          }
          audioMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.AudioMessage audioMessage = 6;</code>
       */
      public AudioMessageOuterClass.AudioMessage.Builder getAudioMessageBuilder() {
        return getAudioMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.AudioMessage audioMessage = 6;</code>
       */
      public AudioMessageOuterClass.AudioMessageOrBuilder getAudioMessageOrBuilder() {
        if ((messageCase_ == 6) && (audioMessageBuilder_ != null)) {
          return audioMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 6) {
            return (AudioMessageOuterClass.AudioMessage) message_;
          }
          return AudioMessageOuterClass.AudioMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.AudioMessage audioMessage = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          AudioMessageOuterClass.AudioMessage, AudioMessageOuterClass.AudioMessage.Builder, AudioMessageOuterClass.AudioMessageOrBuilder> 
          getAudioMessageFieldBuilder() {
        if (audioMessageBuilder_ == null) {
          if (!(messageCase_ == 6)) {
            message_ = AudioMessageOuterClass.AudioMessage.getDefaultInstance();
          }
          audioMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              AudioMessageOuterClass.AudioMessage, AudioMessageOuterClass.AudioMessage.Builder, AudioMessageOuterClass.AudioMessageOrBuilder>(
                  (AudioMessageOuterClass.AudioMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 6;
        onChanged();;
        return audioMessageBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          FileMessageOuterClass.FileMessage, FileMessageOuterClass.FileMessage.Builder, FileMessageOuterClass.FileMessageOrBuilder> fileMessageBuilder_;
      /**
       * <code>.FileMessage fileMessage = 7;</code>
       * @return Whether the fileMessage field is set.
       */
      public boolean hasFileMessage() {
        return messageCase_ == 7;
      }
      /**
       * <code>.FileMessage fileMessage = 7;</code>
       * @return The fileMessage.
       */
      public FileMessageOuterClass.FileMessage getFileMessage() {
        if (fileMessageBuilder_ == null) {
          if (messageCase_ == 7) {
            return (FileMessageOuterClass.FileMessage) message_;
          }
          return FileMessageOuterClass.FileMessage.getDefaultInstance();
        } else {
          if (messageCase_ == 7) {
            return fileMessageBuilder_.getMessage();
          }
          return FileMessageOuterClass.FileMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.FileMessage fileMessage = 7;</code>
       */
      public Builder setFileMessage(FileMessageOuterClass.FileMessage value) {
        if (fileMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          fileMessageBuilder_.setMessage(value);
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>.FileMessage fileMessage = 7;</code>
       */
      public Builder setFileMessage(
          FileMessageOuterClass.FileMessage.Builder builderForValue) {
        if (fileMessageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          fileMessageBuilder_.setMessage(builderForValue.build());
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>.FileMessage fileMessage = 7;</code>
       */
      public Builder mergeFileMessage(FileMessageOuterClass.FileMessage value) {
        if (fileMessageBuilder_ == null) {
          if (messageCase_ == 7 &&
              message_ != FileMessageOuterClass.FileMessage.getDefaultInstance()) {
            message_ = FileMessageOuterClass.FileMessage.newBuilder((FileMessageOuterClass.FileMessage) message_)
                .mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          if (messageCase_ == 7) {
            fileMessageBuilder_.mergeFrom(value);
          }
          fileMessageBuilder_.setMessage(value);
        }
        messageCase_ = 7;
        return this;
      }
      /**
       * <code>.FileMessage fileMessage = 7;</code>
       */
      public Builder clearFileMessage() {
        if (fileMessageBuilder_ == null) {
          if (messageCase_ == 7) {
            messageCase_ = 0;
            message_ = null;
            onChanged();
          }
        } else {
          if (messageCase_ == 7) {
            messageCase_ = 0;
            message_ = null;
          }
          fileMessageBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.FileMessage fileMessage = 7;</code>
       */
      public FileMessageOuterClass.FileMessage.Builder getFileMessageBuilder() {
        return getFileMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.FileMessage fileMessage = 7;</code>
       */
      public FileMessageOuterClass.FileMessageOrBuilder getFileMessageOrBuilder() {
        if ((messageCase_ == 7) && (fileMessageBuilder_ != null)) {
          return fileMessageBuilder_.getMessageOrBuilder();
        } else {
          if (messageCase_ == 7) {
            return (FileMessageOuterClass.FileMessage) message_;
          }
          return FileMessageOuterClass.FileMessage.getDefaultInstance();
        }
      }
      /**
       * <code>.FileMessage fileMessage = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FileMessageOuterClass.FileMessage, FileMessageOuterClass.FileMessage.Builder, FileMessageOuterClass.FileMessageOrBuilder> 
          getFileMessageFieldBuilder() {
        if (fileMessageBuilder_ == null) {
          if (!(messageCase_ == 7)) {
            message_ = FileMessageOuterClass.FileMessage.getDefaultInstance();
          }
          fileMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FileMessageOuterClass.FileMessage, FileMessageOuterClass.FileMessage.Builder, FileMessageOuterClass.FileMessageOrBuilder>(
                  (FileMessageOuterClass.FileMessage) message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        messageCase_ = 7;
        onChanged();;
        return fileMessageBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>.TopLevelData.Type type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.TopLevelData.Type type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.TopLevelData.Type type = 1;</code>
       * @return The type.
       */
      public TopLevelDataOuterClass.TopLevelData.Type getType() {
        @SuppressWarnings("deprecation")
        TopLevelDataOuterClass.TopLevelData.Type result = TopLevelDataOuterClass.TopLevelData.Type.valueOf(type_);
        return result == null ? TopLevelDataOuterClass.TopLevelData.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.TopLevelData.Type type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(TopLevelDataOuterClass.TopLevelData.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.TopLevelData.Type type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <code>fixed64 sendTime = 2;</code>
       * @return The sendTime.
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>fixed64 sendTime = 2;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(long value) {
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 sendTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        
        sendTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TopLevelData)
    }

    // @@protoc_insertion_point(class_scope:TopLevelData)
    private static final TopLevelDataOuterClass.TopLevelData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TopLevelDataOuterClass.TopLevelData();
    }

    public static TopLevelDataOuterClass.TopLevelData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopLevelData>
        PARSER = new com.google.protobuf.AbstractParser<TopLevelData>() {
      @java.lang.Override
      public TopLevelData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TopLevelData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TopLevelData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopLevelData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public TopLevelDataOuterClass.TopLevelData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopLevelData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopLevelData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TopLevelData.proto\032\033business/AudioMess" +
      "age.proto\032\032business/FileMessage.proto\032\033b" +
      "usiness/VideoMessage.proto\032\032business/Wor" +
      "dMessage.proto\"\227\002\n\014TopLevelData\022#\n\013wordM" +
      "essage\030\004 \001(\0132\014.WordMessageH\000\022%\n\014videoMes" +
      "sage\030\005 \001(\0132\r.VideoMessageH\000\022%\n\014audioMess" +
      "age\030\006 \001(\0132\r.AudioMessageH\000\022#\n\013fileMessag" +
      "e\030\007 \001(\0132\014.FileMessageH\000\022 \n\004type\030\001 \001(\0162\022." +
      "TopLevelData.Type\022\020\n\010sendTime\030\002 \001(\006\"0\n\004T" +
      "ype\022\010\n\004WORD\020\000\022\t\n\005AUDIO\020\001\022\t\n\005VIDEO\020\002\022\010\n\004F" +
      "ILE\020\003B\t\n\007messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AudioMessageOuterClass.getDescriptor(),
          FileMessageOuterClass.getDescriptor(),
          VideoMessageOuterClass.getDescriptor(),
          WordMessageOuterClass.getDescriptor(),
        });
    internal_static_TopLevelData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TopLevelData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopLevelData_descriptor,
        new java.lang.String[] { "WordMessage", "VideoMessage", "AudioMessage", "FileMessage", "Type", "SendTime", "Message", });
    AudioMessageOuterClass.getDescriptor();
    FileMessageOuterClass.getDescriptor();
    VideoMessageOuterClass.getDescriptor();
    WordMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
